### ISSUE TITLE
Unused convar will handled as used

### ISSUE THREAD

**Issue by Bara** [alliedmodders/sourcepawn#437] opened 2019-12-23 23:43 UTC
In my test case I found a pretty weird thing with a unused convar that marked as used with `CreateConVar`. I use for both compiler (1.10 and 1.11) the args "-E -O2 -V2".

---

Test case:
```sp
ConVar g_cTest = null;

public void OnPluginStart()
{
    g_cTest = CreateConVar("sm_test", "1", "That's just a test", _, true, 0.0, true, 1.0);
}
```

with compiler 1.10.0.6459:
> cvar_test.sp(5) : error 204: symbol is assigned a value that is never used: "g_cTest"

with compiler 1.11.0.6478 i get no warning (or error with `-E` arg).

**Comment by dvander** [comment] 2019-12-28 19:58
Whoops, this is indeed a regression. The new parser is very aggressive about marking symbols as used, due to the nature of the two-pass compiler and it having to gather as much data as it can in the first pass.

I want to fix this, but it basically depends on removing the two-pass compilation process. I hope to do this in 2020.

**Comment by dvander** [comment] 2021-07-10 17:39
This has been fixed on master.

**Closed by dvander** 2021-07-10 17:39 UTC
Labels: bug
