### ISSUE TITLE
Error on setting string array index to constant

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#400] opened 2019-10-29 11:44 UTC
Unable to set multi dimension char array to constant in 1.11.6455

Error produced:
error 022: must be lvalue (non-constant)

```
#include <sourcemod>

char g_sTest[MAXPLAYERS+1][32];

public void OnPluginStart() {
	g_sTest[1] = "hello"; // error

	char test[2][32];
	test[1] = "test"; // error

	test[1][0] = '\0'; // ok
	g_sTest[1] = test[1]; // ok
}
```

**Comment by asherkin** [comment] 2019-10-29 14:02
According to the original report on Discord this worked pre-1.11, so is likely a regression in the new parser and thus worth looking at.

**Comment by JoinedSenses** [comment] 2019-10-29 14:20
Confirmed to have worked on past versions. Tested on 1.10.0.6380

**Comment by dvander** [comment] 2019-10-29 17:04
This turns out to be a stupid bug, but there are some code generation differences in the example I'd like to understand before I post the fix.

**Comment by Bara** [comment] 2019-10-30 00:28
I'm not pretty sure how related the issue it with my, but got the same error message.
```
void test()
{
    float fTest[3];
    fTest = NULL_VECTOR; // Fine

    float fTest[MAXPLAYERS + 1][3];
    int client = 0;
    fTest[client] = NULL_VECTOR; // error 022: must be lvalue (non-constant)
}
```

if it's another issue, let me know i create new one.

**Comment by dvander** [comment] 2019-10-31 05:53
This is fixed, I will close it once SourceMod has been updated.

**Closed** 2019-11-02 19:33 UTC
Labels: bug
