### ISSUE TITLE
float/int addition issue

### ISSUE THREAD

**Issue by bakugo** [alliedmodders/sourcepawn#424] opened 2019-11-27 22:58 UTC
Consider the following code:

`PrintToChatAll("%f", (-1.0 - 1 + 1));`

When compiled with sourcemod 1.10, it prints `-1.000000`, the expected result
When compiled with sourcemod 1.11, it prints `-1073741824.000000` instead

**Comment by dvander** [comment] 2019-11-29 18:30
Thanks, I can reproduce this. I don't know the root cause yet but I'll look into it soon.

**Comment by Fyren** [comment] 2019-12-01 02:37
https://github.com/alliedmodders/sourcepawn/blob/0af421e3a4eb19c49d96b57061a6a4d86b9bb9a6/compiler/code-generator.cpp#L253

I believe this check isn't getting the right thing done.  We care about `operator+(float, int)`, which isn't commutative, but we're only looking at `ob_add`.

**Comment by dvander** [comment] 2019-12-02 05:22
Thanks, that is indeed the issue... fix incoming, will have a more in-depth writeup in the commit message.

**Comment by dvander** [comment] 2019-12-16 04:49
Thanks, the fix for this is now in SourceMod.

**Closed by dvander** 2019-12-16 04:49 UTC
Labels: bug
