### ISSUE TITLE
#pragma bugs detection of inconsistent indentation

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcepawn#850] opened 2022-10-01 15:56 UTC
The following code causing warning:
```
void SampleTranslation(int client = LANG_SERVER)
{
	#pragma unused client
	PrintToChatAll("Hello World");
}
```
```
warning 217: inconsistent indentation (did you mix tabs and spaces?)
```
despite only tabs are used.

**Comment by dvander** [comment] 2022-10-12 05:14
I can't reproduce this on 1.11 - what compiler did you test on?

**Comment by dvander** [comment] 2022-10-12 05:57
Thanks, this has been fixed on master.

**Comment by dragokas** [comment] 2022-10-12 14:34
dvander,
```
SourcePawn Compiler 1.11.0.6905
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

C:\Users\Alex\Desktop\1.sp(1) : warning 203: symbol is never used: "SampleTranslation"
C:\Users\Alex\Desktop\1.sp(4) : warning 217: inconsistent indentation (did you mix tabs and spaces?)
Code size:         3488 bytes
Data size:         2280 bytes
Stack/heap size:      16452 bytes
Total requirements:   22220 bytes

2 Warnings.
```
I used tabs.

**Comment by dvander** [comment] 2023-07-04 04:12
Can't repro on Windows either.

**Closed by dvander** 2023-07-04 04:12 UTC
Labels: bug, error reporting, compiler
