### ISSUE TITLE
Cannot initialize char array with multiple identical values

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcepawn#569] opened 2021-06-21 19:19 UTC
```
public void OnPluginStart()
{
	char key[128] = {'1', ...};
	//char key[128] = {49, ...}; // same
	
	int k;
	k = key[0];
	PrintToServer("char[0] = %i", k);
	k = key[1];
	PrintToServer("char[1] = %i", k);
	
	// ====================
	
	int b[32] = {49, ...};
	
	PrintToServer("int[0] = %i", b[0]);
	PrintToServer("int[1] = %i", b[1]);
}
```

Log:
```
char[0] = 49
char[1] = 0
int[0] = 49
int[1] = 49
```

**Comment by Fyren** [comment] 2021-06-22 00:26
The issue is the compiler is bad at dealing with arrayss in certain cases and gets confused about element size.  In your case, `key[0]`, `key[4]`, `key[8]`, etc. end up as 49 and the rest are zero.  I don't think you can currently fill a `char[]` using `...` like you tried to do.

This is the same underlying issue as #490, so I'm going to close this issue as duplicate.  (There's probably also at least one ancient report on Bugzilla for the same thing.)

**Closed by Fyren** 2021-06-22 00:26 UTC
Labels: bug, compiler, duplicate
