### ISSUE TITLE
Allow to use recurse call in methodmap

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcepawn#535] opened 2020-12-29 01:19 UTC
Following code snippet raise an error in the line "this.JumpSignature":

```
error 105: cannot find method or property GameDataEx.JumpSignature
```

```
methodmap GameDataEx < KeyValues
{
	public GameDataEx(char[] gameconf)
	{
		char sPath[PLATFORM_MAX_PATH];
		BuildPath(Path_SM, sPath, sizeof(sPath), "gamedata/%s.txt", gameconf);
		
		KeyValues kv = new KeyValues("Games");
		if( !kv.ImportFromFile(sPath) ) {
			LogError("Failed to load \"%s.txt\" gamedata as keyvalues file.", gameconf);
			delete kv;
		}
		return view_as<GameDataEx>(kv);
	}
	
	public bool JumpSignature(char[] name, char gamename[] = "#default")
	{
		if( strcmp(gamename, "#default") == 0 )
		{
			if( this.JumpSignature("csgo") )
			{
				return true;
			}
		}
		
		// ...
	}
}
```
Can you allow this?

Thank you.

**Comment by peace-maker** [comment] 2021-03-22 10:38
Duplicate of #230

**Closed by peace-maker** 2021-03-22 10:38 UTC
