### ISSUE TITLE
Can't return within switch statements if the function it is declared in is the last function in the plugin

### ISSUE THREAD

**Issue by kidfearless** [alliedmodders/sourcepawn#348] opened 2019-08-17 21:29 UTC
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Game/AppID (with version if applicable): 730
  * Current SourceMod version: 1.10.0.6394
  * Current Metamod: Source snapshot: version 1.10.7-dev
  - [X] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [X] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Returning values from within a switch statement that is within the last function of a plugin will cause the following runtime error:

> L 08/17/2019 - 23:19:49: [SM] Exception reported: Instruction contained invalid parameter
L 08/17/2019 - 23:19:49: [SM] Blaming: foo.smx
L 08/17/2019 - 23:19:49: [SM] Call stack trace:
L 08/17/2019 - 23:19:49: [SM]   [1] Line 3, foo::OnPluginStart

The error will not occur if a function is declared after the switch statement, regardless of if that function returns anything. Both floats and ints were tested for return values. Assigning the return value to a variable before or after returning the value still creates the error.

According to Gammacase > 6334 build of 1.10 is the last build that doesn't have that error after that build there was sourcepawn update in 6335 build that "introduced" that error.

# Problematic Code (or Steps to Reproduce)
  ```
#include <sourcemod>
#file "foo"
public void OnPluginStart()
{
	PrintToConsoleAll("%i", FooBar(0));
}
int FooBar(int bar)
{
	switch(bar)
	{
		default:
		{
			return 1;
		}
	}
}
  ```

**Comment by asherkin** [comment] 2019-08-17 22:52
ASM for bad FooBar:
```
CODE 0	; d14
	proc	; FooBar
	; line 6
	break	; d18
	;$lcl bar c
	; line 7
	break	; d1c
	load.s.pri c
	switch 9c
l.9e		; d30
	; line b
	break	; d30
	const.pri 1
	retn
	jump 9d
l.9c		; d48
	casetbl
	case 0 9e
l.9d		; d54
```
(note the double break at the start - which seems to be normal - and jump to the end)

SMX Viewer output for bad FooBar:
```
0xd18: break                           
0xd1c: break                           
0xd20: load.s.pri 0xc                   ; bar
0xd28: switch 0xd48                     ; 3400
0xd30: break                           
0xd34: const.pri 0x1                    ; 1
0xd3c: retn                            
0xd40: jump 0xd54                       ; +0x14
0xd48: casetbl 0x0                      ; 0
```
(note the `case` missing and jump past the end)

With a function after it the codegen is the same, it just doesn't trip the verifier.

**Comment by dvander** [comment] 2019-08-20 04:11
Thanks for catching this, it's quite an edge case... this is a regression from the code validation patch series from last year. SMXViewer seems to be printing something invalid there as well, FWIW.

The problem is that the jump at 0xd40 is invalid, since it points beyond the end of the function. But we would only ever catch this for the last function. During the pre-scanning phase, every jump target looks valid as long as it's within the code section. During the graph building phase, unreachable instructions are ignored. Because the switch statement looks like one giant return statement, we didn't bother generating a return, and thus the jump reaches past the end of the code stream.

I thought of a few ways to fix this:
 - Don't emit the jump. This looks difficult in the single-pass compiler, since we have to process all the cases to know whether it's safe to omit the jump.
 - Tweak GraphBuilder to work around this, but I don't see a sensible way.
 - Always a emit a dead return instruction for these kinds of switch statements.

I'm going with option 3 since that seems the easiest.

**Comment by dvander** [comment] 2019-08-20 04:14
And, thanks asherkin for pointing out that we already had a test case for this!

**Comment by dvander** [comment] 2019-08-20 06:42
This should be fixed on master now.

**Closed by dvander** 2019-08-20 06:42 UTC
