### ISSUE TITLE
Compiler allows no arguments in forwards

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcepawn#258] opened 2018-10-27 12:18 UTC
# Help us help you
  - [-] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [v] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [v] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 1.10.0.6353
  * Current SourceMod snapshot: 1.10.0.6353
  * Current Metamod: Source snapshot:
  - [v] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [v] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [-] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Compiler show no error when you try to compile forward with wrong prototype (without arguments).

# Problematic Code (or Steps to Reproduce)
```
public void OnClientPostAdminCheck()
{
}
```

**Comment by Fyren** [comment] 2018-11-02 20:35
There is probably not anything we can do for this case.  SP explicitly allows ignoring that the declaration has extra parameters so we can append new ones to an existing function (rather than creating a new function).  This helps backwards compatibility.

**Comment by asherkin** [comment] 2018-11-02 21:58
It's probably moderately reasonable for us to report a warning in these cases (or some kind of new lower error level), it's kind of good if old plugins get the extra args added.

**Comment by Fyren** [comment] 2018-11-02 23:17
If that's special cased for only things with a declaration marked as a forward, I think that's fine.  For uses the other way around (natives), it'd be too noisy.

**Comment by VoiDeD** [comment] 2018-11-02 23:37
Might be noisy for forwards as well, `OnPlayerRunCmd` comes to mind. I think its been through a few iterations where new params have been added over time.

**Comment by KyleSanderson** [comment] 2018-11-03 03:36
Yeah; Ryan hit the nail on the head. The test case is working as intended, and for that matter not wrong.

**Comment by dvander** [comment] 2018-11-03 19:34
Indeed it may seem odd but this is part of the language. Closing as works-as-intended.

**Closed by dvander** 2018-11-03 19:34 UTC
