### ISSUE TITLE
Compiler crash on "const char[]"

### ISSUE THREAD

**Issue by dysphie** [alliedmodders/sourcepawn#755] opened 2022-01-22 03:23 UTC
Problematic code: 
```cpp
const char a[];
```

Tested on spcomp 1.11.0.6837

**Comment by Headline** [comment] 2022-01-22 10:12
I suppose it's polite to share what (little) info I deduced from investigating this a little bit.

Not sure what's actually going wrong here but it looks to me like `lexer_->need('=');` isn't erroring us out here. The call after to hier14 is nullptr and our stmts vector length is zero.

https://github.com/alliedmodders/sourcepawn/blob/84adc2f3c518851496fd72aca9909510b9bc1370/compiler/parser.cpp#L668-L672

**Comment by Fyren** [comment] 2022-01-23 19:03
Duplicate of #751.

**Closed by Fyren** 2022-01-23 19:03 UTC
Labels: bug
