### ISSUE TITLE
Assertion `!(sym->usage & uSKIPPED)' failed.

### ISSUE THREAD

**Issue by BotoX** [alliedmodders/sourcepawn#413] opened 2019-11-13 11:01 UTC
test.sp with only:
```
#include <multicolors>
```

hits the assert:
```alliedmodders/sourcemod/sourcepawn/compiler/assembler.cpp:424: void do_call(CellWriter *, AsmReader *, cell): Assertion `!(sym->usage & uSKIPPED)' failed.```

Remove the `#include <multicolors>` (empty file now) and it compiles fine.

Testcase: https://cloud.botox.bz/s/EKzHMNJzoJoHtR3
`./compile.sh`

**Comment by dvander** [comment] 2019-11-24 07:52
This is a bug, but blessedly not a serious one. The job of this assertion is to detect when we emit calls to functions that won't be assembled. The function making the call in this case is unreachable, so there's no chance of a code generation error. However the fact that we're generating code for unreachable functions is also a bug.

The compiler has a bunch of hacks to resolve cases where stocks call other stocks, but basically, these hacks do not work when stock1 calls stock2, which calls stock3, etc... and each call happens before the stock is declared.  The long-term fix for this is to replace parser.cpp. Trying to fiddle with it otherwise is very risky.

I think to make this warning go away, I will add a code generator hack to skip over lines in the assembly buffer belonging to an unreachable function.

**Comment by dvander** [comment] 2019-11-24 08:02
Oh, and - thanks for the great test case, I was able to reproduce this.

**Comment by dvander** [comment] 2019-11-24 21:12
I found a simpler fix - and it looks like this does not need a backport, so I'll close this when SourceMod takes the next SP update.

**Closed** 2019-11-25 22:58 UTC
