### ISSUE TITLE
compiler crash on create variable of type Plugin

### ISSUE THREAD

**Issue by ddorab** [alliedmodders/sourcepawn#874] opened 2023-04-02 19:35 UTC
```cpp
while(iterator.Next())
{
    Plugin plugin = iterator.Plugin;
    ...
}
```

will cause the compiler to crash

```cpp
while(iterator.Next())
{
    Handle plugin = iterator.Plugin;
    ...
}
```
works fine

Edit: forgot to mention, 1.11 compiler

**Comment by peace-maker** [comment] 2023-04-20 14:21
Possible duplicate of #860

**Comment by dvander** [comment] 2023-07-03 04:01
Please re-open if you have a complete test case.

**Closed by dvander** 2023-07-03 04:01 UTC
Labels: bug, compiler
