### ISSUE TITLE
Unable to compile. Compiler thinks endlessly. (#define X X)

### ISSUE THREAD

**Issue by wS-SM** [alliedmodders/sourcepawn#754] opened 2022-01-10 04:49 UTC
```
#define P P

public void OnPluginStart() {
	P("msg");
}
```

C++:
C3861 'P': identifier not found

SM compiler 1.10/1.11:
The compiler thinks endlessly and nothing happens.

**Comment by wS-SM** [comment] 2022-01-10 05:44
If the compiler window is closed, the spcomp process remains open. As a result, I heard 5 short signals that there was a problem with the processor, it turned out that it was 100% loaded.

https://prnt.sc/26bxyeb

**Comment by asherkin** [comment] 2022-01-10 08:50
This is a duplicate of #526 and was fixed in SourcePawn master a while back.

**Closed** 2022-01-10 08:51 UTC
