### ISSUE TITLE
Doing a modulus on variables causes it to ignore the variables sign

### ISSUE THREAD

**Issue by kidfearless** [alliedmodders/sourcepawn#478] opened 2020-05-03 01:41 UTC
test code:
```
public void OnPluginStart()
{
	int i = -1;
	i %= 128;
	int x = -2;
	x = x % 128;
	int z = x % 128;
	PrintToConsoleAll("i:%i x:%i z:%i directly:%i literal:%i", i, x, z, x % 128, -1 % 128);
}
```
return value
```
i:-1 x:-2 z:-2 directly:-2 literal:127
```

**Comment by dvander** [comment] 2020-05-03 02:17
dupe of issue #456

**Closed by dvander** 2020-05-03 02:17 UTC
