### ISSUE TITLE
Function casting problem

### ISSUE THREAD

**Issue by mostten** [alliedmodders/sourcepawn#778] opened 2022-03-06 04:19 UTC
I need to store the method pointer, but when I compile, the compiler reports an error.

Core Plugin:

**CreateNative**("CustomTQuery", **Native_Test**);

public int **Native_Test**(Handle plugin, int argc)
{
    **Function** callback = **GetNativeFunction**(1);
    **SQL_TQuery**(g_hDB, callback, "select * from test");// function prototypes do not match
}

Sub Plugin:

**CustomTQuery**(Test_TCallback);
public void **Test_TCallback**(Handle owner, Handle hndl, const char[] error, any data){}

And then I tried:

SQL_TQuery(g_hDB, view_as<**SQLTCallback**>(callback), "select * from test");

But it's still the same problem.

**Comment by JoinedSenses** [comment] 2022-03-06 04:22
This doesnt appear to be an issue with the compiler. You should join the discord and post more code. Your callback parameters are not matching the definition https://sourcemod.dev/#/dbi/typedef.SQLTCallback

**Comment by mostten** [comment] 2022-03-06 04:44
> This doesnt appear to be an issue with the compiler/language. You should join the discord and post more code. Your callback function is not matching the definition https://sourcemod.dev/#/dbi/typedef.SQLTCallback
> 
> https://discord.gg/HUc67zN

The code is fine, the key problem is "Function" cannot be recognized as "SQLTCallback", The latest version cannot be converted in view_as.

**Comment by JoinedSenses** [comment] 2022-03-06 04:47
Youre gonna have to share more code, especially your callback function declaration.

**Comment by mostten** [comment] 2022-03-06 04:57
> Youre gonna have to share more code, especially your callback function declaration. This is not an instance where view_as should even be used. The error is pretty explicit there - `function prototypes do not match`. Your callback method more than likely does not match the definition for SQLTCallback.

public void Test_TCallback(Handle owner, Handle hndl, const char[] error, any data){}

There is nothing wrong with the code, in 1.10 this is ok, but the latest version it's error.

**Comment by JoinedSenses** [comment] 2022-03-06 05:02
ah, i misunderstood the issue. Its passing in a generic function but doesnt know the callback does or doesnt match. Im not sure a way around that.

**Comment by mostten** [comment] 2022-03-06 05:13
> ah, i misunderstood the issue. Its passing in a generic function but doesnt know the callback does or doesnt match. Im not sure a way around that.
> 
> I understand now, sorry. I didnt pay attention to GetNativeFunction. I receive the same error in 1.10
> 
> 

In 1.10 we can use view_as, For example:
SQL_TQuery(g_hDB, view_as<SQLTCallback>(callback), "select * from test");

**Comment by JoinedSenses** [comment] 2022-03-06 05:15
yes, youre right. im tired and didnt pay attention to you retrieving function from GetNativeFunction and thought it was a function existing already in code.

**Comment by asherkin** [comment] 2022-03-06 11:29
Duplicate of #671, but it looks like you've found a concrete case where this actually causes a problem (passing it to something else to call it), so it would be useful to add this test case to that issue.

**Closed by asherkin** 2022-03-06 11:29 UTC
Labels: duplicate
